### ISSUE TITLE
Error when using browserify

### ISSUE THREAD

**Issue by call-a3** [One-com/rfc2047#1]
When trying to produce a browserify bundle that depends on this module, the following error is thrown:

```
Cannot find module 'iconv' from '.../node_modules/rfc2047/lib'
```

I suspect browserify doesn't handle [lib/rfc2047.js:22](https://github.com/One-com/rfc2047/blob/master/lib/rfc2047.js#L22) very well. (The try-catch is only effective at runtime, not while bundleing.)

**Comment by papandreou** [comment]
The -i switch seems to fix it: `browserify -i iconv lib/rfc2047.js`

If it's part of a larger build, however, it would be annoying to have to do that in the topmost project, so I've just added a workaround that makes browserify unable to detect that require at all: https://github.com/One-com/rfc2047/commit/393351d43c59ffbff24c9e5ab28ce794cc072abb

Released in 1.0.1.
