### ISSUE TITLE
Sometimes wrong encoding of subsequent emojis

### ISSUE THREAD

**Issue by dilyanpalauzov** [One-com/rfc2047#11]
```javascript
import rfc2047 from 'rfc2047'

console.log(rfc2047.encode('Subject: Seven hills😍🦌'));
console.log(rfc2047.encode('Subject: Seven h😍🦌'));
```
prints
```
Subject: Seven =?utf-8?Q?hills=F0=9F=98=8D=EF=BF=BD?= =?utf-8?Q?=EF=BF=BD?=
Subject: Seven =?utf-8?Q?h=F0=9F=98=8D=F0=9F=A6=8C?=
```
I decode the output headers at https://dogmamix.com/MimeHeadersDecoder/ .

The first output line is correct, the second output line is not correct.  The difference in the both inputs is just `ills`.

**Comment by papandreou** [comment]
Nice catch! Turns out it was due to `String#substr` breaking the emojis depending on the offset. Published a fix in 4.0.0.
