### ISSUE TITLE
Skipped space after encoded word

### ISSUE THREAD

**Issue by dilyanpalauzov** [One-com/rfc2047#13]
```javascript
import rfc2047 from 'rfc2047'
console.log(rfc2047.encode("uvwxy-München <board@uvwxy-muenchen.de>"))
```
prints `=?utf-8?Q?uvwxy-M=C3=BC?=nchen <board@uvwxy-muenchen.de>`.

In terms of RFC2047 `=?utf-8?Q?uvwxy-M=C3=BC?=` is an encoded word, a word that is not followed by a space.  Is this valid?  RFC2047 is not explicit on this, it says that encoded words are designed to be recognized as 'atom's by an RFC 822 parser.  That parser sees two atoms in a row, which atoms are not separated by CFWS.  Atoms must be separated by CFWS.

Irrespective of whether the above header is valid, please tweak the rfc2047 module to avoid such syntax.  I am aware of a MUA, which for the above header displays a space between the encoded word and nchen.

Output of `=?utf-8?Q?uvwxy-M=C3=BCnchen?= <board@uvwxy-muenchen.de>` is better.

**Comment by papandreou** [comment]
PR welcome 🤗
