### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by rstoye** [One-com/rfc2047#6]
Hello there,

my team and I are using this package in one of our applications at work. We are close to distributing the application to our customer and wanted to round up everything we need including licenses and everything we need for that.

According to [npm](https://www.npmjs.com/package/rfc2047) your library is licensed under the BSD license. However the source code here on Github has no license file, which leaves us with the question whether it can be used commercially or not.

Furthermore the [BSD license](https://en.wikipedia.org/wiki/BSD_licenses) is a license family with different versions that have different restrictions, so the second question would be: Which license does it fall under (0-, 2-, 3- or 4-clause BSD)?

If you could provide us with these information we would be much obliged.

**Comment by papandreou** [comment]
Sorry for the licensing situation being unclear. Added a `BSD-3-Clause` license now.
